<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVsrJpl5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVsrJpl5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVsrJpl5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVsrJpl5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVsrJpl5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VsrJpl5',
    'container.build_id' => '86b13cc8',
    'container.build_time' => 1523699892,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVsrJpl5');
